name: Build and Test
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Automated tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [ 'chrome', 'firefox', 'edge' ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant permission
        run: chmod +x gradlew

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Run tests in ${{ matrix.browser }}
        run: ./gradlew runTest -Dbrowser=${{ matrix.browser }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports
          path: test-output/