name: Build and Test
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [ 'chrome', 'firefox', 'edge' ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Change permission
        run: chmod +x gradlew

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Run tests in different browsers
        run: ./gradlew runTest -Dbrowser=${{ matrix.browser }}